
import React, { useMemo } from 'react';
import { RoadmapInitiative } from '../types';

interface RoadmapTimelineProps {
  initiatives: RoadmapInitiative[];
  companyName: string;
}

const PRIORITY_COLORS: Record<string, string> = {
  High: 'bg-rose-50 text-rose-700 border-rose-200',
  Medium: 'bg-amber-50 text-amber-700 border-amber-200',
  Low: 'bg-emerald-50 text-emerald-700 border-emerald-200',
};

const CATEGORY_COLORS: Record<string, string> = {
  'Product': 'bg-indigo-100 text-indigo-800',
  'Engineering': 'bg-blue-100 text-blue-800',
  'Marketing': 'bg-pink-100 text-pink-800',
  'Sales': 'bg-orange-100 text-orange-800',
  'Strategy': 'bg-violet-100 text-violet-800',
  'Infrastructure': 'bg-slate-100 text-slate-800',
};

export const RoadmapTimeline: React.FC<RoadmapTimelineProps> = ({ initiatives, companyName }) => {
  const quarters = ['Q1', 'Q2', 'Q3', 'Q4'] as const;

  const categories = useMemo(() => {
    const uniqueCategories = Array.from(new Set(initiatives.map((i) => i.category)));
    return uniqueCategories.sort();
  }, [initiatives]);

  const getInitiativesForCell = (category: string, quarter: string) => {
    return initiatives.filter((i) => i.category === category && i.quarter === quarter);
  };

  const getCategoryColor = (cat: string) => {
    const key = Object.keys(CATEGORY_COLORS).find(k => cat.includes(k)) || 'Strategy';
    return CATEGORY_COLORS[key] || 'bg-gray-100 text-gray-800';
  };

  const exportToCSV = () => {
    const headers = ['Category', 'Quarter', 'Priority', 'Title', 'Description'];
    const rows = initiatives.map(i => [
      `"${i.category}"`,
      `"${i.quarter}"`,
      `"${i.priority}"`,
      `"${i.title.replace(/"/g, '""')}"`,
      `"${i.description.replace(/"/g, '""')}"`
    ]);
    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `${companyName.replace(/\s+/g, '_')}_Roadmap.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="mt-8 space-y-4">
      {/* Action Bar */}
      <div className="flex justify-between items-center no-print">
        <p className="text-gray-500 text-sm italic">
          Visualization: Strategic Matrix View
        </p>
        <div className="flex gap-2">
          <button 
            onClick={exportToCSV}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-sm font-semibold text-gray-700 hover:bg-gray-50 hover:border-indigo-300 transition-all shadow-sm active:scale-95"
          >
            <svg className="w-4 h-4 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export CSV
          </button>
          <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-semibold hover:bg-indigo-700 transition-all shadow-sm active:scale-95"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 00-2 2h2m2 4h10a2 2 0 002-2v-3a2 2 0 00-2-2H5a2 2 0 00-2 2v3a2 2 0 002 2zm0 0v-9a2 2 0 012-2h10a2 2 0 012 2v9" />
            </svg>
            Save as PDF
          </button>
        </div>
      </div>

      {/* Hidden Header for PDF/Print */}
      <div className="hidden roadmap-export-header text-center p-8 bg-indigo-50 rounded-2xl border border-indigo-100">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Product Strategy Roadmap</h1>
        <h2 className="text-xl text-indigo-600 font-semibold">{companyName}</h2>
        <p className="text-gray-500 mt-2 text-sm">Generated by StrategyFlow AI on {new Date().toLocaleDateString()}</p>
      </div>

      <div className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden print:border-none print:shadow-none">
        <div className="overflow-x-auto">
          <table className="w-full border-collapse min-w-[800px]">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-200">
                <th className="p-4 text-left text-xs font-bold text-gray-400 uppercase tracking-widest border-r border-gray-200 w-48">
                  Focus Area
                </th>
                {quarters.map((q) => (
                  <th key={q} className="p-4 text-center border-r border-gray-200 last:border-r-0">
                    <div className="flex flex-col items-center">
                      <span className="text-sm font-bold text-gray-900">{q}</span>
                      <span className="text-[10px] text-gray-400 font-medium">2025 Plan</span>
                    </div>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {categories.map((category, catIdx) => (
                <tr key={category} className={catIdx % 2 === 0 ? 'bg-white' : 'bg-gray-50/30'}>
                  <td className="p-4 border-r border-b border-gray-200 align-top">
                    <span className={`inline-block px-3 py-1 rounded-lg text-xs font-bold whitespace-nowrap ${getCategoryColor(category)} shadow-sm border border-black/5`}>
                      {category}
                    </span>
                  </td>
                  {quarters.map((q) => {
                    const items = getInitiativesForCell(category, q);
                    return (
                      <td key={`${category}-${q}`} className="p-3 border-r border-b border-gray-200 last:border-r-0 align-top min-w-[200px]">
                        <div className="space-y-3">
                          {items.length > 0 ? (
                            items.map((item, idx) => (
                              <div 
                                key={idx} 
                                className="group relative bg-white p-4 rounded-xl border border-gray-200 shadow-sm hover:border-indigo-400 hover:shadow-md transition-all cursor-default print:break-inside-avoid"
                              >
                                <div className="flex justify-between items-start mb-2">
                                  <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded border ${PRIORITY_COLORS[item.priority] || 'bg-gray-50'}`}>
                                    {item.priority}
                                  </span>
                                  <div className="flex gap-1 no-print">
                                    <div className="w-1.5 h-1.5 rounded-full bg-indigo-400"></div>
                                  </div>
                                </div>
                                <h4 className="text-xs font-bold text-gray-900 mb-1 leading-tight group-hover:text-indigo-600 transition-colors">
                                  {item.title}
                                </h4>
                                <p className="text-[11px] text-gray-500 leading-normal line-clamp-2 print:line-clamp-none">
                                  {item.description}
                                </p>
                                
                                {/* Tooltip on hover - Hidden in print */}
                                <div className="absolute z-10 hidden group-hover:block no-print left-0 top-full mt-2 w-64 bg-gray-900 text-white p-3 rounded-lg text-[11px] shadow-xl pointer-events-none">
                                  <div className="font-bold mb-1 border-b border-gray-700 pb-1">{item.title}</div>
                                  {item.description}
                                </div>
                              </div>
                            ))
                          ) : (
                            <div className="h-12 border border-dashed border-gray-200 rounded-xl bg-gray-50/30 flex items-center justify-center print:hidden">
                              <span className="text-[10px] text-gray-300 font-medium italic">Available Slot</span>
                            </div>
                          )}
                        </div>
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="bg-gray-50 p-4 border-t border-gray-200 flex justify-between items-center text-[11px] text-gray-500">
          <div className="flex gap-4">
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-rose-400"></span> High Priority
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-amber-400"></span> Medium Priority
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-400"></span> Low Priority
            </span>
          </div>
          <div className="italic font-medium">
            Generated by StrategyFlow AI
          </div>
        </div>
      </div>
    </div>
  );
};
